### ISSUE TITLE
install.bashでapt updateが実行されていない

### ISSUE THREAD

**Issue by tikisi** [OmeSatoFoundation/ome2023#12]
https://github.com/OmeSatoFoundation/ome2023/blob/8c19189e8e797095c05acd503fa9eb0d9821364f/contrib/scripts/install.bash#L98

**Comment by RollMan** [comment]
* [X] apt update が実行できるようにする
* [ ] 同じ理由で動作しないであろう `chroot $MOUNT_POINT su -c 'xdg-user-dirs-update' pi
` の挙動をチェックする
* [ ] サブシェルを bash とする
