### ISSUE TITLE
FaBoの検品(個人用#33~#39, 班用#D~#I)

### ISSUE THREAD

**Issue by sugasin2813** [OmeSatoFoundation/ome2023#120]
Task List
- [ ] 袋に内蔵のBricksのリストに書かれた部品があるかどうかを確認
- [ ] 各Bricksの動作チェック

もし欠品or動作不良が見つかればその旨を[spreadsheet](https://uaizuacjp-my.sharepoint.com/:x:/g/personal/m5271508_o365_u-aizu_ac_jp/EarD6DkZbXJNvPkzXOioTDQBqGMGH8wf3uUVf7XLxDKp0g?e=KUl6S6)の備考欄に追記する。

**Comment by motegi210** [comment]
## 6/28 Faboチェック 33~39, D ~ I
### センサー
#### digout.hsp
- LED
- 振動子

#### digin.hsp
- ボタン
- スイッチ
- リミットスイッチ
- 傾斜センサー

#### anain.hsp
- 感圧センサー
- ボリューム
- 照度センサー

#### kyori.hsp
- 距離センサー

#### oled.hsp
- 有機LEDディスプレイ

### ケーブル
- すべてのケーブルを一度は使用し、動作することを確認した

### シート
- すべての入力ピンで動作することを確認、確認に使用したセンサーは以下に記載
#### デジタル入力
- ボタン
#### アナログ入力
- 感圧センサー

詳細はスプレッドシートに記載
