### ISSUE TITLE
Recovery Account

### ISSUE THREAD

**Issue by RollMan** [OmeSatoFoundation/ome2023#28]
講義中に受講生がパスワードを忘れた等の時に対応するための管理用ユーザーを作成する。

ユーザー名: ome
パスワード: 

https://omesato.cloud.mattermost.com/main/pl/o4d3eb8mspyqpr5x155973f73c (internal link)

**Comment by yutashx** [comment]
次の理由により、Recovery Accountの作成は不要になりました。
> 別のLinuxマシンにSDカードリーダーを取り付けることで、ext4 FSを読み出すことが出来ます。そこで、ルート権限で、一時的に簡易パスワードを設定して、子どもたちにその場で変更させる方が、良い対処かもしれません。
https://omesato.cloud.mattermost.com/main/pl/hb63tx41zf8gubncihizckjuwy (internal link)

そのためこのissueはcloseします。
