### ISSUE TITLE
第７回 cgi演習用のhspファイルが動作しない

### ISSUE THREAD

**Issue by twinkletia** [OmeSatoFoundation/ome2023#61]
- led.hsp, ir.hsp
sh: 1: gpio: not foundと出て、LEDがひからない。原因は調査中

- querystring.hsp
sh: 1: decurl.py: not foundと出て、期待動作しない。cgi.as内でcmdexec decurl.pyのような記述があるが、どのディレクトリを参照しているのか？（２０１９の場合、/home/pi/ome/binにあった）

- sensors.hsp, sensors_table.hsp
~~プログラムに問題なく、httpは正常(200レスポンス)だが、ブラウザが「このページは動作していません ERR_INBALID_HTTP_RESPONSE」と出て、温度が表示されない。原因は調査中~~
私が間違えてローカルな古いスクリプトを適用したのが原因で、PR #63 版のスクリプトで期待動作しました。

**Comment by RollMan** [comment]
decurl.py を追加します！その他はおまかせします．

gpio コマンドは，これはシェルコマンドだったと思いますが，もしかすると 400 では動作しないのかもしれません．

**Comment by twinkletia** [comment]
decurl.pyの追加＆情報ありがとうございます。

**Comment by twinkletia** [comment]
whichした結果gpioコマンドはPi400環境に存在しないことを確認。
https://github.com/OmeSatoFoundation/ome2019/issues/153 にissueとして挙がっていたので、こちらを参考に修正する。

**Comment by tikisi** [comment]
Pi400環境にデフォルトでインストールされている`raspi-gpio`コマンドがあります。

こちを利用する場合のGPIO 17に対してオンオフをする命令例
ON: `raspi-gpio set 17 op pn dh`
OFF: `raspi-gpio set 17 dl`

**Comment by twinkletia** [comment]
ありがとうございます。試してみます。
